services:
  java-server:
    build: ./dockerComposeJava
    ports:
      - "9090:9090"
    networks:
      - app-network

  python-client:
    build: ./dockerComposepython
    depends_on:
      - java-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
